### ISSUE TITLE
Raster download: User defined pixel size is not respected when requested area is tiled TOPDESK 2406 0023

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/lizard-qgis-plugin#32]
When the requested extent is too large, the raster is downloaded in tiles. However, in such a case, the pixel size that is set by the user is not respected

**Comment by ldebek** [comment]
@leendertvanwolfswinkel Could you please add some more details of the problematic case? Like what was the: raster name, extent and pixel size defined?

**Comment by leendertvanwolfswinkel** [comment]
Raster name is "Hoogte AHN4"
Pixel size requested by the user is 0.5x0.5
Extent I don't know, but large enough to force tiling of rasters
